



#define FM_PID_P_GAIN 1.3  //Gain setting for the pitch and roll P-controller (default = 1.3).
#define FM_PID_I_GAIN 0.005 //Gain setting for the pitch and roll I-controller (default = 0.04).
#define FM_PID_D_GAIN 20   //Gain setting for the pitch and roll D-controller (default = 18.0).

#define  FM_MANUAL_GAIN 2.0

#define RC_CALIBRATION_CONFIG true
#define RC_CALIBRATION_CHANNEL_1_MAX 1935
#define RC_CALIBRATION_CHANNEL_1_MIN 1111
#define RC_CALIBRATION_CHANNEL_2_MAX 1943
#define RC_CALIBRATION_CHANNEL_2_MIN 1106
#define RC_CALIBRATION_CHANNEL_3_MAX 1950
#define RC_CALIBRATION_CHANNEL_3_MIN 1110
#define RC_CALIBRATION_CHANNEL_4_MAX 1935
#define RC_CALIBRATION_CHANNEL_4_MIN 1104
#define RC_CALIBRATION_CHANNEL_5_MAX 1800
#define RC_CALIBRATION_CHANNEL_5_MIN 1000
#define RC_CALIBRATION_CHANNEL_6_MAX 1895
#define RC_CALIBRATION_CHANNEL_6_MIN 1011



#define IMU_CALIBRATION_CONFIG true
#define IMU_INPUT_CALIBRATION_SAMPLES 500
#define IMU_CALIBRATION_PITCH  0
#define IMU_CALIBRATION_ROLL 0

#define IMU_CALIBRATION_YAW -52.1528358

#define IMU_FILTER_PREVIOUS (float)0.0
#define IMU_FILTER_NEW (float)1.0
