



#define FM_PID_P_GAIN 1.3  //Gain setting for the pitch and roll P-controller (default = 1.3).
#define FM_PID_I_GAIN 0.005 //Gain setting for the pitch and roll I-controller (default = 0.04).
#define FM_PID_D_GAIN 20   //Gain setting for the pitch and roll D-controller (default = 18.0).

#define FM_PID_P_INCREMENTS 0.1
#define FM_PID_I_INCREMENTS 0.01
#define FM_PID_D_INCREMENTS 1.0

#define FM_CONTROL_INTERVAL_MS 20


#define  FM_MANUAL_GAIN 2.0

#define HMI_UART_USART1 1
#define HMI_UART_USART2 2
#define HMI_UART_SELECT HMI_UART_USART2

#define RC_THROTTLE_CHANNEL RC_CH_2
#define RC_YAW_CHANNEL RC_CH_1
#define RC_PITCH_CHANNEL RC_CH_3
#define RC_ROLL_CHANNEL RC_CH_4
#define RC_ESTOP_CHANNEL RC_CH_5

#define RC_CHANNEL_1_CONFIG (RC_INPUT_INPUT_NORMAL | RC_INPUT_INPUT_RANGE_CENTERED)
#define RC_CHANNEL_2_CONFIG (RC_INPUT_INPUT_REVERSED | RC_INPUT_INPUT_RANGE_ZEROED)
#define RC_CHANNEL_3_CONFIG (RC_INPUT_INPUT_NORMAL | RC_INPUT_INPUT_RANGE_CENTERED)
#define RC_CHANNEL_4_CONFIG (RC_INPUT_INPUT_NORMAL | RC_INPUT_INPUT_RANGE_CENTERED)
#define RC_CHANNEL_5_CONFIG (RC_INPUT_INPUT_NORMAL | RC_INPUT_INPUT_RANGE_CENTERED)
#define RC_CHANNEL_6_CONFIG (RC_INPUT_INPUT_NORMAL | RC_INPUT_INPUT_RANGE_CENTERED)

#define FM_MIX_MOTOR_1_PITCH -1.0f
#define FM_MIX_MOTOR_1_ROLL  -1.0f
#define FM_MIX_MOTOR_1_YAW   -1.0f

#define FM_MIX_MOTOR_2_PITCH  1.0f
#define FM_MIX_MOTOR_2_ROLL  -1.0f
#define FM_MIX_MOTOR_2_YAW    1.0f

#define FM_MIX_MOTOR_3_PITCH  1.0f
#define FM_MIX_MOTOR_3_ROLL   1.0f
#define FM_MIX_MOTOR_3_YAW   -1.0f

#define FM_MIX_MOTOR_4_PITCH -1.0f
#define FM_MIX_MOTOR_4_ROLL   1.0f
#define FM_MIX_MOTOR_4_YAW    1.0f

#define RC_CALIBRATION_CONFIG true
#define RC_CALIBRATION_CHANNEL_1_MAX 1935
#define RC_CALIBRATION_CHANNEL_1_MIN 1111
#define RC_CALIBRATION_CHANNEL_2_MAX 1943
#define RC_CALIBRATION_CHANNEL_2_MIN 1106
#define RC_CALIBRATION_CHANNEL_3_MAX 1950
#define RC_CALIBRATION_CHANNEL_3_MIN 1110
#define RC_CALIBRATION_CHANNEL_4_MAX 1935
#define RC_CALIBRATION_CHANNEL_4_MIN 1104
#define RC_CALIBRATION_CHANNEL_5_MAX 1800
#define RC_CALIBRATION_CHANNEL_5_MIN 1000
#define RC_CALIBRATION_CHANNEL_6_MAX 1895
#define RC_CALIBRATION_CHANNEL_6_MIN 1011



#define IMU_CALIBRATION_CONFIG true
#define IMU_INPUT_CALIBRATION_SAMPLES 500
#define IMU_CALIBRATION_PITCH  0
#define IMU_CALIBRATION_ROLL 0

#define IMU_CALIBRATION_YAW -52.1528358

#define IMU_INPUT_PITCH_SIGN -1.0f
#define IMU_INPUT_ROLL_SIGN  -1.0f
#define IMU_INPUT_YAW_SIGN    1.0f

#define IMU_FILTER_PREVIOUS (float)0.0
#define IMU_FILTER_NEW (float)1.0
